#! /bin/sh

# Border Colors
bspc config normal_border_color "#18191B"
bspc config focused_border_color "#18191B"


bspc monitor DP-4 -d 1 2 3
bspc monitor HDMI-0 -d 4 5 6
bspc config focus_follows_pointer true
bspc config border_width         2
bspc config window_gap          25

# Golden Number \o/
bspc config split_ratio          0.618
bspc config borderless_monocle   false
bspc config gapless_monocle      false

## park app to WS
#WS1
#WS2
bspc rule -a Chromium desktop='^2'
bspc rule -a Firefox desktop='^4'
#WS3
bspc rule -a Spotify desktop='^3'
#WS4
#WS5
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


## Float Apps
bspc rule -a Mirage state=floating center=on
bspc rule -a Nemo state=floating center=on
bspc rule -a Pcmanfm state=floating center=on
bspc rule -a feh state=floating center=on
bspc rule -a File-roller state=floating center=on
bspc rule -a Pavucontrol state=floating center=on
bspc rule -a VirtualBox Machine state=floating center=on
bspc rule -a mpv state=floating center=on
bspc rule -a Firefox:Places state=floating center=on
# Polybar
$HOME/.config/i3/polybar.sh
 
# Screen Orientation
xrandr --output HDMI-0 --mode 1920x1080 --pos 1920x0 --rotate normal --output DP-4 --mode 1920x1080 --pos 0x0 --rotate normal --primary

# Wallpaper
wall=/nfs/wallpapers/pen-colors.jpg
$HOME/.scripts/setwall.sh $wall

# spring_crocus_2-wallpaper-3840x1080.jpg

# Corsair Utility
ckb-next -b

~/.scripts/xstart.sh

notify-send -t 3000 "bspwm reloaded"
